version: '3.8'

services:
  # 前端服务
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # 对于开发环境，使用相对路径，依赖Vite代理
      # 对于生产环境，可以通过主机名访问
      - VITE_API_BASE_URL=/api
      - DOCKER_ENV=true
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - schedule-network
    restart: unless-stopped

  # 后端服务
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - schedule-network
    restart: unless-stopped

  # MySQL数据库
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - schedule-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin数据库管理界面
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    depends_on:
      - mysql
    networks:
      - schedule-network
    restart: unless-stopped

# 数据卷
volumes:
  mysql_data:
    driver: local

# 网络
networks:
  schedule-network:
    driver: bridge